from sentence_transformers import SentenceTransformer
import numpy as np
from transformers import AutoTokenizer

user_query = "what is blackwell's outlook for 2025?"

context = """
symbol	reportedDate	speaker	text
NVDA	2025-11-19	Stewart Stecker	Good afternoon, everyone, and welcome to NVIDIA Corporation's conference call for the fourth quarter of fiscal 2025. With me today from NVIDIA Corporation are Jensen Huang, president and chief executive officer, and Colette Kress, executive vice president and chief financial officer. I'd like to remind you that our call is being webcast live on NVIDIA Corporation's Investor website. The webcast will be available for replay until the conference call to discuss our financial results for the first quarter of fiscal 2026. The content of today's call is NVIDIA Corporation's property. It cannot be reproduced or transcribed without prior written consent. During this call, we may make forward-looking statements based on current expectations; these are subject to a number of significant risks and uncertainties, and our actual results may differ materially. A discussion of factors that could affect our future financial results and business can be found in today's earnings release. Our most recent forms 10-K and 10-Q, and the reports that we may file on form 8-K with the Securities and Exchange Commission. All our statements are made as of today, February 26, 2025, based on information currently available to us. Except as required by law, we assume no obligation to update any such statements. During this call, we will discuss non-GAAP financial measures. Reconciliation of these non-GAAP financial measures to GAAP financial measures is in our CFO commentary, which is posted on our website. With that, let me turn the call over to Colette.
NVDA	2025-11-19	Colette Kress	Thanks, Stewart. Q4 was another record quarter. Revenue of $39.3 billion was up 12% sequentially and up 78% year on year. And above our outlook of $37.5 billion. For fiscal 2025, revenue was $130.5 billion, up 114% from the prior year. Let's start with data center. Data center revenue for fiscal 2025 was $115.2 billion, more than doubling from the prior year. In the fourth quarter, it is in a revenue of $35.6 billion was a record, up 16% sequentially and 93% year on year. As the Blackwell ramp commenced, and Hopper 200 continued to contribute growth. In Q4, Blackwell sales exceeded our expectations. We delivered $11 billion of Blackwell revenue to meet strong demand. This is the fastest product ramp in our company's history, unprecedented in its speed and scale. Blackwell production is in full gear across multiple configurations, and we are increasing supply quickly, expanding customer adoption. Our Q4 data center compute revenue jumped 18% sequentially and over 2x year on year. Customers are racing to scale infrastructure to train the next generation of cutting-edge models and unlock the next level of AI capabilities. With Blackwell, it will be common for these clusters to start with 100,000 GPUs or more. Shipments have already started for multiple infrastructures of this size. Post-training and model customization are fueling demand for NVIDIA Corporation infrastructure and software as developers and enterprises leverage techniques such as fine-tuning, reinforcement learning, and distillation to tailor models for domain-specific use cases. Hugging Face alone hosts over 90,000 derivatives traded from the Llama Foundation model. The scale of post-training and model customization is massive and can collectively demand orders of magnitude more compute than pretraining. Our inference demand is accelerating, driven by test time scaling and new reasoning models. Like OpenAI's O3, DeepSeq R1, and Grok 3. Long-thinking reasoning AI can require... (line truncated to 2000 chars)
NVDA	2025-11-19	C.J. Muse	Yeah. Good afternoon. Thank you for taking the question. I guess, for me, Jensen, as test time compute and reinforcement learning shows such promise, we're clearly seeing increasing blurring in the lines between training and inference. What does this mean for the potential future of potentially inference-dedicated clusters? And how do you think about the overall impact to NVIDIA Corporation and your customers? Thank you.
NVDA	2025-11-19	Jensen Huang	Yeah. I appreciate that, C.J. There are now multiple scaling laws. There's the pretrained scaling laws. And that's going to continue to scale because we have multimodality. We have data that came from reasoning that are now used to pretraining. And then the second is post-training scaling law. Using reinforcement learning human feedback, reinforcement learning AI feedback, reinforcement learning verifiable rewards, the amount of computation you use for post-training is actually higher than pretraining. And it makes sense in the sense that you could, while you're using reinforcement learning, generate an enormous amount of synthetic data or synthetically generated tokens. AI models are basically generating tokens to train AI models. That's post-train. And the third part, this is the part that you mentioned, is test time compute or reasoning. Long-thinking, inference scaling. Basically, the same ideas. And you have chain of thought, you have search. The amount of tokens generated, the amount of inference compute needed is already a hundred times more than the one-shot examples and the one-shot capabilities of large language models in the beginning, and that's just the beginning. This is just the beginning. The idea that the next generation could have thousands of times and even hopefully extremely thoughtful and simulation-based and search-based models that could be hundreds of thousands, millions of times more compute than today is in our future. And so the question is, how do you design such an architecture? Some of the models are autoregressive, and some of the models are diffusion-based. Sometimes you want your data center to have disaggregated inference. Sometimes it's compact. And so it's hard to figure out what is the best configuration for a data center, which is the reason why NVIDIA Corporation's architecture is so popular. We run every model. We are great at training. The vast majority of our compute today is actually inference,... (line truncated to 2000 chars)
NVDA	2025-11-19	Joseph Moore	I wonder if you could talk about GV200 at CES. You sort of talked about the complexity of the rack-level systems and the challenges you have. And then, as you said in the prepared remarks, we've seen a lot of general availability. You know, where are you in terms of that ramp? Are there still bottlenecks to consider at a systems level above and beyond the chip level? And just you know, have you maintained your enthusiasm for the NVLink 72 platforms?
NVDA	2025-11-19	Jensen Huang	Well, I'm more enthusiastic today than I was at CES. And the reason for that is because we shipped a lot more to CES. We have some 350 plants manufacturing the one and a half million components that go into each one of the Blackwell racks. Base Blackwell racks. Yes. It's extremely complicated. And we successfully and incredibly ramped up Grace Blackwell, delivering some $11 billion of revenues last quarter. We're going to have to continue to scale as demand is quite high, and customers are anxious and impatient to get their Blackwell systems. You'd probably seen on the web a fair number of celebrations about Grace Blackwell Systems coming online and we have them, of course. We have a fairly large installation of Grace Blackwell for our own engineering and our own design teams and software teams. Coreweave has now gone public about the successful bring-up of theirs. Microsoft has. Of course, OpenAI has. And you're starting to see many come online. So I think the answer to your question is nothing is easy about what we're doing. But we're doing great, and all of our partners are doing great.
NVDA	2025-11-19	Vivek Arya	Thank you for taking my question. Could I just you wouldn't mind confirming if Q1 is the bottom for gross margins? And then, Jensen, my question is for you. What is on your dashboard to give you the confidence that the strong demand can sustain into next year and has DeepSeq and whatever innovations they came up with, has that changed that view in any way? Thank you.
NVDA	2025-11-19	Colette Kress	Let me first take the first part of the question. Regarding the gross margin. During our Blackwell ramp, our gross margins will be in the low seventies. At this point, we are focusing on expediting our manufacturing. Expediting our manufacturing is to make sure that we can provide customers as soon as possible. Our Blackwell is fully ramped. And once it does, I'm sorry. Blackwell fully ramps, we can improve our cost and our gross margin. So we expect to probably be in the mid-seventies later this year. You know, walking through what you heard Jensen speak about the systems and their complexity. They are customizable in some cases. They've got multiple networking options, have liquid cool and water-cooled. So we know there is an opportunity for us to improve these gross margins going forward. But right now, we are going to focus on getting the manufacturing plate into our customers as soon as possible.
NVDA	2025-11-19	Jensen Huang	We know several things, Vivek. We have a fairly good line of sight of the amount of capital investment that data centers are building out towards. We know that going forward, the vast majority of software is going to be based on machine learning. And so accelerated computing and generative AI, reasoning AI, are going to be the type of architecture you want in your data center. We have, of course, forecast and plans from our top partners. And we also know that there are many innovative, really exciting startups that are still coming online. As new opportunities for developing the next breakthroughs in AI, whether it's agentic AIs, reasoning AIs, or physical AIs. The number of startups is still quite vibrant, and each one of them needs a fair amount of computing infrastructure. So I think whether it's the near-term signals or the mid-term signals. Near-term signals, of course, are POs and forecasts and things like that. Mid-term signals would be the level of infrastructure and CapEx scale out compared to previous years. And then the long-term signals it has to do with the fact that we know fundamentally software has changed. From hand coding that runs on CPUs through machine learning and AI-based software that runs on GPUs and accelerated computing systems. So we have a fairly good sense that this is the future of software. And then maybe as you roll it out, another way to think about that is we've really only touched consumer AI and search and some amount of consumer generative AI. Advertising, recommenders, kind of the early days of software. The next wave's coming. Agentic AI for enterprise, physical AI for robotics, and Sovereign AI have different regions build out their AI for their own ecosystems. And so each one of these are barely off the ground, and we can see them. We can see them because, you know, obviously, we're in the center of much of this development. And we can see great activity happening in all these different places. A... (line truncated to 2000 chars)
NVDA	2025-11-19	Matt Ramsay	Yeah. Good afternoon. Thanks for taking my question. Your next generation Blackwell Ultra is set to launch in the second half of this year in line with the team's annual product cadence. Jensen, can you help us understand the demand dynamics for Ultra given that you'll still be ramping the current generation Blackwell solutions? How do your customers and the supply chain also manage the simultaneous ramps of these two products, and is the team still on track to execute Blackwell Ultra in the second half of this year?
NVDA	2025-11-19	Jensen Huang	Yes. Blackwell Ultra is second half. As you know, the first Blackwell had a hiccup that probably cost us a couple of months. We're fully recovered, of course. The team did an amazing job recovery. And all of our supply chain partners and just so many people helped us recover at the speed of light. And so now we've successfully ramped production of Blackwell. But that doesn't stop the next train. The next train is, you know, it's on an annual rhythm. Blackwell Ultra, with new networking, new memories, and, of course, new processors, and all of that is coming online. We've been working with all of our partners and customers laying this out. They have all of the necessary information. And we'll work with everybody to do the proper transition this time between Blackwell, and Blackwell Ultra, the system architecture is exactly the same. It's a lot harder going from Hopper to Blackwell because we went from an NVLink 8 system to a NVLink 72 base system. So the chassis, the architecture of the system, the hardware, the power delivery, all of that had to change. This was quite a challenging transition. But the next transition will slot right in. Grace Blackwell Ultra will slot right in. We've also already revealed and have been working very closely with all of our partners on the click after that, and the click after that is called Vera Rubin. And all of our partners are getting up to speed on the transition of that. And so preparing for that transition and again, we're going to provide a big, big, huge step up. So come to GTC, and I'll hold on to you about Blackwell Ultra, Vera Rubin, and then show you what's the one click after that. Really, really exciting new product, so come to GTC, please.
NVDA	2025-11-19	Timothy Arcuri	Thanks a lot. Jensen, we hear a lot about custom ASICs. Can you kind of speak to the balance between custom ASIC and merchant GPU? We hear about some of these heterogeneous super clusters to use both GPU and ASIC. Is that something customers are planning on building or will these infrastructures remain fairly distinct? Thanks.
NVDA	2025-11-19	Jensen Huang	Well, we build very different things than ASICs. In some ways, completely different in some areas we intercept. We're different in several ways. One, NVIDIA Corporation's architecture is general. You know, whether you've optimized for autoregressive models or diffusion-based models or vision-based models or multimodal models or text models. We're great in all of it. We're great in all of it because our software stack is so our architecture is responsible. Our software stack is ecosystem is so rich that we're the initial target of, you know, most exciting innovations and algorithms. And so by definition, we're much, much more general than narrow. We're also really good from end to end—from data processing, the curation of the training data, to the training of the data, of course, to reinforcement learning used in post-training, all the way to inference with test time scaling. So, you know, we're general. We're end to end. And we're everywhere. And because we're not in just one cloud, we're in every cloud, we could be on-prem. We could be in, you know, in a robot. Our architecture is much more accessible and a great target initial target for anybody who's starting up a new company. And so we're everywhere. And then the third thing I would say is that our performance and our rhythm is so incredibly fast. Remember that these data centers are always fixed in size. They're fixed in size or they're fixed in power. And if our performance per watt is anywhere from 2x to 4x to 8x, which is not unusual, it translates directly to revenues. And so if you have a 100-megawatt data center, if the performance or the throughput that 100-megawatt or that gigawatt data center is four times or eight times higher, your revenues for that gigawatt data center is eight times higher. And the reason that is so different than data centers of the past is because AI factories are directly monetizable through the tokens generated. And so the token throughput of our ar... (line truncated to 2000 chars)
NVDA	2025-11-19	Ben Reitzes	Yeah. Hi. Ben Reitzes here. Hey. Thanks a lot for the question. Hey, Jensen. It's a geography-related question. You know, you did a great job explaining some of the demand underlying, you know, factors here on the strength. But the US was up about $5 billion or so sequentially. And I think, you know, there is a concern about whether the US can pick up the slack if there's regulations towards other geographies. And I was just wondering as we go throughout the year, you know, if this kind of surge in the US continues and it's going to be whether that's okay. And if that underlies your growth rate, how can you keep growing so fast with this mix shift towards the US? Your guidance looks like China is probably up sequentially. So just wondering if you could go through that dynamic and maybe Colette can weigh in. Thanks a lot.
NVDA	2025-11-19	Jensen Huang	China is approximately the same percentage as Q4 and as in previous quarters. It's about half of what it was before the export control. But it's approximately the same in percentage. With respect to geographies, the takeaway is that AI is software. It's modern software. It's incredible modern software. But it's modern software. And AI has gone mainstream. AI is used in delivery services everywhere, shopping services everywhere. You know? You were to buy a quart of milk delivered to you. AI was involved. And so almost everything that a consumer service provides AI is at the core of it. Every student will use AI as a tutor. Health care services use AI. Financial services use AI. No fintech company will not use AI. Every fintech company will. Climate tech companies use AI. Mineral discovery now uses AI. The number of every higher education, every university uses AI. So I think it is fairly safe to say that AI has gone mainstream and that it's being integrated into every application. And our hope is that, of course, the technology continues to advance safely and advance in a helpful way to our society. And with that, you know, we're I do believe that we're at the beginning of this new transition. And what I mean by that in the beginning is, remember behind us, there have been decades of data centers and decades of computers that have been built. And they've been built for a world of hand coding and general-purpose computing and CPUs and so on and so forth. And going forward, I think it's fairly safe to say that that world is going to be almost all software will be infused with AI. All software and all services will be based on ultimately based on machine learning, and the data flywheel is going to be part of improving software and services. That the future computers will be accelerated. The future computers will be based on AI. And we're really three years into that journey. And in modernizing computers that have taken decades to build out. ... (line truncated to 2000 chars)
NVDA	2025-11-19	Aaron Rakers	Yeah. Thanks for letting me back in. Jensen, I'm curious as we now approach the two-year anniversary of really the Hopper inflection that you saw in 2023 in Gen AI in general. We think about the roadmap you have in front of us. How do you think about the infrastructure that's been deployed from a replacement cycle perspective and whether, you know, if it's GV300 or if it's the Rubin cycle where we start to see maybe some refresh opportunity. I'm just curious to how you look at that.
NVDA	2025-11-19	Jensen Huang	Yeah. I appreciate it. First of all, people are still using Voltas, Pascals, and Amperes. And the reason for that is because they're always things that because CUDA is so programmable, you could use it right well, one of the major use cases right now is data processing and data curation. You find a circumstance that an AI model is not very good at? You present that circumstance to a vision language model, let's say. Let's say it's a car? You present that circumstance to a vision language model. The vision language model actually looks at the circumstances. It's a this isn't this is what happened, and I wasn't very good at it. You then take that response, this the prompt, and you go and prompt an AI model to find in your whole link of data of other circumstances like that. Whatever that circumstance was. And then you use an AI to do domain randomization and generate a whole bunch of other examples. And then from that, you can go train the model. And so you could use the Amperes to go and do data processing and data curation and machine learning-based search. And then you create the training dataset, which you then present to your Hopper systems for training. And so each one of these architectures are completely compatible, and so everything runs on everything. But if you have infrastructure in place, you can put the less intensive workloads onto the installed base of the past. All of our CPUs are very well employed.
NVDA	2025-11-19	Atif Malik	Hi. Thank you for taking my question. I have a follow-up question on gross margins, Colette. I understand there are many moving parts that will yield and NVLink 72 and Ethernet mix. And you kind of tiptoed the earlier question if April quarter is the bottom. But second half would have to ramp, like, 200 basis points per quarter to get to the mid-seventies range that you're giving for the end of the fiscal year. And we still don't know much about the tariff impact on the broader semiconductor. So what kind of gives you the confidence in that trajectory in the back half of this year?
NVDA	2025-11-19	Colette Kress	Yeah. Thanks for the question. Our gross margins are quite complex in terms of the material and everything that we put together in a Blackwell system. There is a tremendous amount of opportunity to look at a lot of different pieces of that, and how we can better improve our gross margins over time. Remember, we have many different configurations as well on Blackwell that will be able to help us do that. So, together, working after we get some of these really strong ramping completed for our customers, we can begin a lot of that work. If not, we're going to probably start as soon as possible. If we can improve it in the short term, we will also do that. Tariffs, at this point, are a little bit of an unknown. It's an unknown until we understand further what the US government's plan is, its timing, where, and how much. So at this time, we are awaiting, but again, we would, of course, always follow export control and or tariffs in that manner.
NVDA	2025-11-19	Jensen Huang	No. No. I'm gonna just wanna thank you. Up to, Jensen? And, like, the medium, a couple of things. I just wanna thank you. Thank you, Colette. Demand for Blackwell is extraordinary. AI is evolving beyond perception and generative AI into reasoning. With reasoning AI, we're observing another scaling law. Inference time or test time scaling. The more computation, the more the model thinks, the smarter the answer. Models like OpenAI's Grok 3, DeepSeq R1, are reasoning models that apply inference time scale. Reasoning models can consume a hundred times more compute. Future reasoning models can consume much more compute. DeepSeq R1 has ignited global enthusiasm. It's an excellent innovation. But even more importantly, it has open-sourced a world-class reasoning AI model. Nearly every AI developer is applying R1 or chain of thought and reinforcement learning techniques like R1 to scale their model's performance. We now have three scaling laws, as I mentioned earlier, driving the demand for AI computing. The traditional scaling laws of AI remain intact. Foundation models are being enhanced with multimodality, and pretraining is still growing. But it's no longer enough. We have two additional scaling dimensions. Post-training scaling, where reinforcement learning fine-tuning, model distillation require orders of magnitude more compute than pretraining alone. Inference time scaling and reasoning where a single query can demand a hundred times more compute. We designed Blackwell for this moment—a single platform that can easily transition from pretraining, post-training, and test time scaling. Blackwell's MP4 transformer engine and NVLink 72 scale-up fabric and new software technologies let Blackwell process reasoning AI models 25 times faster than Hopper. Blackwell, in all of these configurations, is in full production. Each Grace Blackwell NVLink 72 rack is an engineering marvel. One and a half million components produced across 350 manufacturing... (line truncated to 2000 chars)

"""

model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(tx_flat["text"].to_list())

len(embeddings), embeddings[0].shape

query_emb = model.encode(user_query)

similarities = np.dot(embeddings, query_emb) / (
    np.linalg.norm(embeddings, axis=1) * np.linalg.norm(query_emb)
)
len(similarities), similarities[0]
k = 5

top_k_idx = np.argsort(similarities)[-k:][::-1]
results = tx_flat.to_pandas().iloc[top_k_idx]


tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
test_data = """

Jensen Huang	Yeah. I appreciate that, C.J.
There are now multiple scaling laws. There's the pretrained scaling laws.
And that's going to continue to scale because we have multimodality.
We have data that came from reasoning that are now used to pretraining.
And then the second is post-training scaling law.
Using reinforcement learning human feedback, reinforcement learning AI feedback,
reinforcement learning verifiable rewards, the amount of computation you use
for post-training is actually higher than pretraining.
And it makes sense in the sense that you could, while you're using reinforcement learning,
generate an enormous amount of synthetic data or synthetically generated tokens.
AI models are basically generating tokens to train AI models.
That's post-train. And the third part, this is the part that you mentioned,
is test time compute or reasoning. Long-thinking, inference scaling.
Basically, the same ideas. And you have chain of thought, you have search.
The amount of tokens generated, the amount of inference compute needed
is already a hundred times more than the one-shot examples
and the one-shot capabilities of large language models in the beginning,
and that's just the beginning. This is just the beginning.
The idea that the next generation could have thousands of times
and even hopefully extremely thoughtful and simulation-based and search-based models
that could be hundreds of thousands, millions of times more compute than today
is in our future. And so the question is, how do you design such an architecture?
Some of the models are autoregressive, and some of the models are diffusion-based.
Sometimes you want your data center to have disaggregated inference.
Sometimes it's compact. And so it's hard to figure out
what is the best configuration for a data center,
which is the reason why NVIDIA Corporation's architecture is so popular.
We run every model. We are great at training.
The vast majority of our compute today is actually inference,
and Blackwell takes all of that to a new level.
We designed Blackwell with the idea of reasoning models in mind.
And you look at training, it's many times more performant.
But what's really amazing is that for long-thinking,
test time scaling reasoning AI models, we're tens of times faster,
25 times higher throughput. And so Blackwell is going to be incredible
across the board. And when you have a data center that allows you to configure
and use your data center based on are you doing more pretraining now,
post-training now, or scaling out your inference, our architecture is fungible
and easy to use in all of those different ways.
And so we're seeing, in fact, much, much more concentration
of a unified architecture than ever before.

"""
tokens = tokenizer(test_data, truncation=True, max_length=1000)
len(tokens["input_ids"])
